default_platform(:mac)

platform :mac do

  desc "Release a new version with a patch bump_type"
  lane :patch do
    release("patch")
  end

  desc "Release a new version with a minor bump_type"
  lane :minor do
    release("minor")
  end

  desc "Release a new version with a major bump_type"
  lane :major do
    release("major")
  end

  def release(type)
    pod_lib_lint(allow_warnings: true,
		 sources: [ENV["PODSPEC_SOURCE"]])
    version = version_bump_podspec(path: ENV["PODSPEC_NAME"],
                                   bump_type: type)
    git_add(path: ENV["PODSPEC_NAME"])
    git_commit(path: [ENV["PODSPEC_NAME"]],
               message: "#{version} release")
    add_git_tag(tag: "#{version}")
    push_to_git_remote
    pod_push(path: ENV["PODSPEC_NAME"],
	     repo: ENV["PODSPEC_REPO"],
	     allow_warnings: true,
	     sources: [ENV["PODSPEC_SOURCE"]])
  end
end